// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using testExperis.Data;

namespace testExperis.Migrations
{
    [DbContext(typeof(AlumnosContext))]
    [Migration("20200314210908_firtsTestExperis")]
    partial class firtsTestExperis
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("testExperis.Models.Alumnos", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("documento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("edad")
                        .HasColumnType("int");

                    b.Property<int>("estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("fechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<string>("nombres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("semestre")
                        .HasColumnType("int");

                    b.Property<double>("telefonoMovil")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.ToTable("alumnos");
                });

            modelBuilder.Entity("testExperis.Models.Materias", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Alumnosid")
                        .HasColumnType("int");

                    b.Property<string>("descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("estado")
                        .HasColumnType("int");

                    b.Property<string>("nombreMateria")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("Alumnosid");

                    b.ToTable("materias");
                });

            modelBuilder.Entity("testExperis.Models.Notas", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Alumnosid")
                        .HasColumnType("int");

                    b.Property<double>("documento")
                        .HasColumnType("float");

                    b.Property<int>("estado")
                        .HasColumnType("int");

                    b.Property<int>("nota")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Alumnosid");

                    b.ToTable("notas");
                });

            modelBuilder.Entity("testExperis.Models.Salones", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Alumnosid")
                        .HasColumnType("int");

                    b.Property<int>("estado")
                        .HasColumnType("int");

                    b.Property<string>("letra")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("numero")
                        .HasColumnType("int");

                    b.Property<string>("sede")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("Alumnosid");

                    b.ToTable("salones");
                });

            modelBuilder.Entity("testExperis.Models.Materias", b =>
                {
                    b.HasOne("testExperis.Models.Alumnos", "Alumnos")
                        .WithMany("Materias")
                        .HasForeignKey("Alumnosid");
                });

            modelBuilder.Entity("testExperis.Models.Notas", b =>
                {
                    b.HasOne("testExperis.Models.Alumnos", "Alumnos")
                        .WithMany("Nota")
                        .HasForeignKey("Alumnosid");
                });

            modelBuilder.Entity("testExperis.Models.Salones", b =>
                {
                    b.HasOne("testExperis.Models.Alumnos", "Alumnos")
                        .WithMany("Salones")
                        .HasForeignKey("Alumnosid");
                });
#pragma warning restore 612, 618
        }
    }
}
